### ISSUE TITLE
Sprite Benchmark

### ISSUE THREAD

**Issue by JFixbi** [nicolasgramlich/AndEngineExamples#3]
01-29 15:05:12.501: E/AndEngine(6322): AndEngine
01-29 15:05:12.501: E/AndEngine(6322): org.andengine.util.system.SystemUtils$SystemUtilsException: java.lang.NumberFormatException: unable to parse '1000000
01-29 15:05:12.501: E/AndEngine(6322): ' as integer
01-29 15:05:12.501: E/AndEngine(6322):  at org.andengine.util.system.SystemUtils.readSystemFileAsInt(SystemUtils.java:254)
01-29 15:05:12.501: E/AndEngine(6322):  at org.andengine.util.system.SystemUtils.getCPUFrequencyCurrent(SystemUtils.java:177)
01-29 15:05:12.501: E/AndEngine(6322):  at org.andengine.examples.benchmark.BaseBenchmark$6.call(BaseBenchmark.java:208)
01-29 15:05:12.501: E/AndEngine(6322):  at org.andengine.examples.benchmark.BaseBenchmark$6.call(BaseBenchmark.java:1)
01-29 15:05:12.501: E/AndEngine(6322):  at org.andengine.util.ActivityUtils$1.doInBackground(ActivityUtils.java:122)
01-29 15:05:12.501: E/AndEngine(6322):  at org.andengine.util.ActivityUtils$1.doInBackground(ActivityUtils.java:1)
01-29 15:05:12.501: E/AndEngine(6322):  at android.os.AsyncTask$2.call(AsyncTask.java:185)
01-29 15:05:12.501: E/AndEngine(6322):  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
01-29 15:05:12.501: E/AndEngine(6322):  at java.util.concurrent.FutureTask.run(FutureTask.java:137)
01-29 15:05:12.501: E/AndEngine(6322):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1068)
01-29 15:05:12.501: E/AndEngine(6322):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:561)
01-29 15:05:12.501: E/AndEngine(6322):  at java.lang.Thread.run(Thread.java:1096)
01-29 15:05:12.501: E/AndEngine(6322): Caused by: java.lang.NumberFormatException: unable to parse '1000000
01-29 15:05:12.501: E/AndEngine(6322): ' as integer
01-29 15:05:12.501: E/AndEngine(6322):  at java.lang.Integer.parse(Integer.java:433)
01-29 15:05:12.501: E/AndEngine(6322):  at java.lang.Integer.parseInt(Integer.java:422)
01-29 15:05:12.501: E/AndEngine(6322):  at java.lang.Integer.parseInt(Integer.java:382)
01-29 15:05:12.501: E/AndEngine(6322):  at org.andengine.util.system.SystemUtils.readSystemFileAsInt(SystemUtils.java:250)
01-29 15:05:12.501: E/AndEngine(6322):  ... 11 more

**Comment by nicolasgramlich** [comment]
Hm, what device / os version are you on?

**Comment by JFixbi** [comment]
it looks like a parsing problem,

anyway - Samsung Galaxy S
